### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by tapkain** [hurshi/dio-http-cache#1]
Thank you @hurshi for the awesome package! I got a few questions, maybe you can add the answers in the future to README?
- how to invalidate manually the cache? should I set max-age to 0? (when user makes pull to refresh for example)
- how to delete ALL items from cache (when the user logs in with another account)

**Comment by hurshi** [comment]
Thanks for your report, I have updated [README](https://github.com/hurshi/dio-http-cache), and add some [example](https://github.com/hurshi/dio-http-cache/blob/master/example/lib/main.dart).
And this is my suggestion for your question:
*  `_manager.delete(url);`
* ` _manager.clearAll();`
