### ISSUE TITLE
incompatible with newer dependencies

### ISSUE THREAD

**Issue by skaionedev** [hurshi/dio-http-cache#105]
Because json_serializable ^4.0.1 depends on analyzer >=0.41.2 <2.0.0 and freezed 1.0.0 depends on analyzer ^2.7.0, json_serializable ^4.0.1 is incompatible with freezed 1.0.0.
And because no versions of freezed match >1.0.0 <2.0.0, json_serializable ^4.0.1 is incompatible with freezed ^1.0.0.
So, because app_market depends on both freezed ^1.0.0 and json_serializable ^4.1.4, version solving failed.
pub get failed (1; So, because app_market depends on both freezed ^1.0.0 and json_serializable ^4.1.4, version solving failed.)

**Comment by FDuhen** [comment]
For those having the same question, this project looks abandoned.
Another similar project is currently maintained : https://pub.dev/packages/dio_cache_interceptor

**Comment by ilovelinux** [comment]
Not related with this project.
