### ISSUE TITLE
remove date when logout 

### ISSUE THREAD

**Issue by osamamohammed98** [hurshi/dio-http-cache#106]
After logging out and then logging back in again, the previous data will be preserved unless you close the application permanently and then open it again

![image](https://user-images.githubusercontent.com/27555246/145035287-927bf97d-1041-493f-ade4-ab69581a42be.png)

![image](https://user-images.githubusercontent.com/27555246/145035342-d4101d31-8675-4d19-88ba-16481a44535a.png)

![image](https://user-images.githubusercontent.com/27555246/145035398-c023d7e3-6b57-4e44-b48b-5b940655a8aa.png)

**Comment by TianyongWang** [comment]
来信已收到
