### ISSUE TITLE
没有网络时依旧使用了缓存

### ISSUE THREAD

**Issue by itMcdull** [hurshi/dio-http-cache#15]
没有网络的情况下,默认强制刷新的数据也使用了缓存,我希望没有网络的时候正常调用,不使用缓存;     使用clearAll();清掉之后依旧还是使用了缓存,
![image](https://user-images.githubusercontent.com/40596015/68913374-0181e400-0796-11ea-8c3e-4045b8165a79.png)
设置maxStale天数也没有生效,
dio版本dio: 3.0.4
diohttp_cache:0.2.0
flutter:1.9.1+hotfix.6

**Comment by itMcdull** [comment]
没有网络时请求一个post接口,报错如下
![image](https://user-images.githubusercontent.com/40596015/68922221-0787bd00-07b6-11ea-9518-cd38af30f39a.png)

**Comment by hurshi** [comment]
Hi，非常感谢你的反馈。

1. 缓存：在这里我是这样设计的：

   1. 当本地缓存在 maxAge 时间内，直接返回本地缓存；
   2. 当本地缓存超过 maxAge 时间，则请求网络。
   3. 当网络请求失败，则去查看本地缓存，如果本地缓存时间在 maxAge 或者 maxStale 时间内，则返回缓存。(maxAge 一般都小于 maxStale)

2. forceRefresh 使用场景：当本地缓存在 maxAge 时间内，如果使用了 forceRefresh，则会直接请求网络而不使用缓存，如果请求网络失败了还是会上面 iii 的流程。

3. > 没有网络时请求一个post接口,报错如下: NoSuch.......

   这个问题在新版中已经解决，参考讨论：https://github.com/hurshi/dio-http-cache/issues/11

4. >  我希望没有网络的时候正常调用,不使用缓存：

   我的理解是如果请求失败了就返回失败，不要再返回缓存中的内容对吧？如果是这种情况，可以不设置 maxStale 或者直接设为 0.

5. > 使用clearAll();清掉之后依旧还是使用了缓存

   先使用新版 [0.2.3](https://pub.dev/packages/dio_http_cache), 如果还有问题，请贴上更详细的代码哈。

**Comment by itMcdull** [comment]
Hi 非常感谢你的解答。
    1. ```我的理解是如果请求失败了就返回失败，不要再返回缓存中的内容对吧？如果是这种情况，可以不设置 maxStale 或者直接设为 0.```
   是的，您的理解没有错。但是我并没有设置maxStale.接口一直在使用缓存
我在关闭wifi和数据流量之后，打印response.extra如下：
```{dio_cache_max_age: 24:00:00.000000, dio_cache_force_refresh: true}```
可以看到没有maxStale，并且dio_cache_force_refresh为true, 如果我没有理解错的话，forceRefresh为true应该是不使用缓存，但是实际返回的应该是请求失败的结果，而不是maxAge没过期就一直获取缓存的数据，
 2. clearAll()需要重新启动程序才会触发，目前来看是这样的。
附上代码
![image](https://user-images.githubusercontent.com/40596015/69021472-de07a500-09f2-11ea-8d26-4622571d58e9.png)

**Comment by hurshi** [comment]
Hi，
1. dio-http-cache 在定义拦截器的时候，主要拦截了3个方法： onRequest, onResponse, onError.

2. 对于 dio-http-cache 这个库，我的定位是尽最大可能，能使用缓存则使用缓存而不做多余的网络请求。所以对于 forceRefresh，只是在请求的时候跳过缓存，仅此而已。（对应于上面说的 onRequest）。

3. 不论是否设置过 forceRefresh，或者其他的什么，只要请求出错了(onError)，我就会尝试从本地提取缓存提供给调用者使用。(有数据总比什么都没有好吧，前提是缓存数据没有过期)。

4. 对于你的需求，我觉得在这种情况下，可以直接请求网络而不使用缓存；

   如果有其他理由非得使用缓存的话，这里有个临时方案：

   ```dart
   // 先删掉本地关于这条记录的缓存
   _dioCacheManager.deleteXxx();
   // 再请求数据
   _dio.request...
   ```

   **但不建议使用这个临时方案**，我理解的缓存目的这么几个：

   1. 减轻服务器负担；
   2. 加速本地数据的显示；
   3. 做弱网/无网情况下，也能显示数据；

   **可是你的场景下，我感觉没有缓存什么事**。

5. dio-http-cache 在初始化的时候（程序初次打开或者重新启动的时候），会自动清理已过期的缓存。而`clearAll()`是即时生效的，我这边也反复测试过了，如果你的确发现这里有 bug，不知是否方便在 github 上写个小 demo 复现呢？**我这边如果能复现的话肯定会优先解决的**，**非常感谢你**。

**Comment by itMcdull** [comment]
稍后我会写一个关于clearAll()的demo,如果还有复现,我将上传至github,感谢你的解答,
