### ISSUE TITLE
Response data type is String when setting ResponseType.bytes 

### ISSUE THREAD

**Issue by ricpar11** [hurshi/dio-http-cache#20]
Wrapping the options property of a get request with buildCacheOptions in this way: 
`dio.get(
        url,
        options: buildCacheOptions(Duration(days: 7),
            options: Options(responseType: ResponseType.bytes))
 );`

The response data property is an _String_ that contains correct data ("[1,23,232...]") but it's not a **List of ints** ([1,23,232]).
Is that the expected behaviour , or it's a bug?

**Comment by ricpar11** [comment]
I just realized it only happens when the response is cached, the first time the request's response is a list of int, as expected.

**Comment by hurshi** [comment]
Hello, thanks for your feedback. 
Yes, it's a bug. and it has fixed in new version: [0.2.5](https://pub.dev/packages/dio_http_cache)
