### ISSUE TITLE
关于通过拦截器设置缓存策略的几点疑问？

### ISSUE THREAD

**Issue by walkermanx** [hurshi/dio-http-cache#21]
@hurshi  您好 
首先很感谢您开源的网络框架 我看了您的文档 现在有如下疑问：
1、通过拦截器设置的缓存策略是否可以称之为全局缓存策略？也就是设置全局缓存策略后，同一个baseUrl下的所有请求都会采用这一策略进行缓存，所以只有当个别请求需要采用和全局缓存不一致的策略的时候 才需要在请求的时候通过option进行针对性设置；
2、通过拦截器设置缓存策略的baseUrl参数如果为空 是否就代表针对后续的所有请求(不管其baseUrl是什么)，该缓存策略都会生效？或者baseUrl 是否支持多个取值？
3、目前通过拦截器设置的缓存策略（全局策略 如果我理解无误的话），是否可以支持指定接口请求类型的缓存过滤（比如，只针对GET进行缓存 排除POST PUT等）

**Comment by hurshi** [comment]
### Hi,非常感谢你的提问
1. 这个拦截器是由 Dio 提供的，只要是同一个 Dio 实例，设置过这个拦截器，之后都会调用这个拦截器；但是调用了拦截器并不意味着就缓存接口了，要对某个接口进行缓存必须显示地调用 `options: buildCacheOptions...` ，所以这里**没有**所谓的全局缓存策略，只能为每个接口单独设置。
2. 和 baseUrl 没有关系，baseUrl 是参数是可选的。对于 dio-http-cache 来说，baseUrl 是 key 的组成部分。
3. 暂时没有对请求类型做过滤。

### 其他
* **全局缓存策略**这个功能看上去的确有存在的必要，但我个人觉得也没有那么必要吧，毕竟缓存的接口相对于所有接口一般只是占一小部分，设置了全局缓存后，必须为每个不需要缓存的接口显示地设置跳过缓存。
* **欢迎提出你的想法**，共同交流才能使 dio-http-cache 更好用。

**Comment by walkermanx** [comment]
@hurshi 很感谢你的回复  扫清了我的疑惑  其实目前 dio-http-cache 只是一个单纯的数据缓存库。即强制缓控制 并没有完整实现http缓存机制 （比如对比缓存（缓存校验））因此目前我们接口如果返回304状态码应该也是不支持的对吧？

**Comment by hurshi** [comment]
对的，的确没有完整实现 http 缓存机制。
但是这里也有初步的实现，比如 maxAge, maxStale 等
