### ISSUE TITLE
请问楼主，这个缓存的获取策略是什么？如果想要先获取缓存数据显示，接着获取网络数据，等网络数据回来之后覆盖的话要怎么实现呢

### ISSUE THREAD

**Issue by chenchengyin** [hurshi/dio-http-cache#26]
1、默认的获取数据的逻辑
2、本地和网络策略实现的建议

**Comment by hurshi** [comment]
https://github.com/hurshi/dio-http-cache/blob/master/README.md

**Comment by jinxing88** [comment]
> https://github.com/hurshi/dio-http-cache/blob/master/README.md

看了文档，只有两种缓存策略啊，貌似不支持先获取缓存数据，紧接着从网络获取数据覆盖吧

**Comment by xujinping** [comment]
的确不支持先读取本地缓存，在获取网络数据覆盖。目前看了只支持

**Comment by xujinping** [comment]
的确不支持先读取本地缓存，在获取网络数据覆盖。目前看了只支持
1.没设置强制刷新（默认没设置），从缓存读取未过期的数据，缓存有数据，直接返回，缓存没数据从网络返回数据
2.设置了强制刷新
 2.1 先从网络获取数据，
 2.2 获取数据成功，写入缓存，返回数据
 2.3 获取数据失败，返回缓存数据
