### ISSUE TITLE
支持缓存图片吗

### ISSUE THREAD

**Issue by Dovvvis** [hurshi/dio-http-cache#28]
支持缓存图片吗,将来会支持吗

**Comment by hurshi** [comment]
Hi，非常感谢你的反馈，你可以看看[cached-images](https://flutter.dev/docs/cookbook/images/cached-images)
为保持的精简，本项目只会做网络接口的缓存，不会支持图片缓存。
后期即使要做，也会另开一个项目，而不会在本项目中写。
