### ISSUE TITLE
切换网络会产生bug

### ISSUE THREAD

**Issue by scoyzhao** [hurshi/dio-http-cache#29]
切换网络以后，请求接口数据变化，但是只能请求到旧的数据，而且response的code和status都是null

**Comment by hurshi** [comment]
Hi，非常感谢你的 issue，
但是我按照以下步骤，没能重现。如果你能描述更加详细的重现步骤，或者提供一个能必先的Demo，那就再好不过了。不管如何，非常感谢你。

### 我的操作步骤：
1. 运行 dio-http-cache 的 example。
2. 在 Post demo 中，先用WiFi请求 https://www.wanandroid.com/article/query/0/json  ，请求参数是`k=flutter`。获得数据，并且code是200。
3. 关闭WiFi，打开流量，在上面接口的前提下，更改请求参数为 `k=android`。也能正常获取数据，并且code是200。

**Comment by hurshi** [comment]
Hi, Thousands of years have passed.
我先关闭此 issue，如果复现了随时开启这个 issue 哈。
感谢~~~
