### ISSUE TITLE
缓存primaryKey 能将请求类型也加入么? 避免同一个path 不同请求类型 缓存出现错乱

### ISSUE THREAD

**Issue by walkermanx** [hurshi/dio-http-cache#37]
1、目前我同一个path 有一个GET请求 一个是PUT请求 发现两者缓存会出现混乱 GET请求的时候会加载到PUT请求的缓存  虽然目前通过认为设置subKey避免了 但觉得可以优化一下
2、希望可以设置可以缓存的请求类型 ,或者缓存只针对GET请求 对于非GET请求 比如POST/PUT等操作类请求默认不缓存 或者可以设置为不缓存

**Comment by hurshi** [comment]
Hi，非常感谢你的 issue
我已经在新版（0.2.7）中添加这个功能并且已经发布。
请升级新版本体验看看，有任何问题请尽管在这里讨论。
