### ISSUE TITLE
Make http-cache available for Flutter WEB

### ISSUE THREAD

**Issue by fvisticot** [hurshi/dio-http-cache#39]
Any plan to provide support for Flutter WEB ?

**Comment by hurshi** [comment]
Hi, Thanks for your advice.
This is not planned for the time being, but will probably be added later by the future trend of Flutter- Web

**Comment by fvisticot** [comment]
Flutter Web will be stable in the coming month.
It would be very nice to have WEB support for our current app with minimum changes.
My current application is using http-cache and due to sqlite dependency, the app can not run on WEB.
A solution will be to use sembast plugin (WEB ready).
