### ISSUE TITLE
Make all async method await-able

### ISSUE THREAD

**Issue by tapkain** [hurshi/dio-http-cache#4]
Currently, almost all methods inside cache manager are asynchronous by nature but they are not marked as async, so you cannot await them to make a delete operation before retrieving from the cache. 
```
delete(String key, {String subKey}) {
    key = _convertMd5(key);
    if (null != subKey) subKey = _convertMd5(subKey);

    _memoryCacheStore?.delete(key, subKey: subKey);
    _diskCacheStore?.delete(key, subKey: subKey);
  }
```

**Comment by hurshi** [comment]
Thank you for correcting my mistake.  
I have fixed it in the new version.
