### ISSUE TITLE
Cache is not working on mobile device, but works perfectly on Emulators

### ISSUE THREAD

**Issue by ch3ckmat3** [hurshi/dio-http-cache#40]
Hi,

Just implemented the cache plugin and it works perfectly on Android Emulator, returns data from cache when Airplane mode is on. But when the app is deployed on a physical device, either in debug or release mode, the cache doesn't work at all. No error messages can be seen in the debug log as well. What am I missing here?

**Comment by hurshi** [comment]
Hi, thanks for your issue:
I'm sorry I don't know what is wrong with your access, have you tried running the [example](https://github.com/hurshi/dio-http-cache/tree/master/example) on your real machine?
