### ISSUE TITLE
无法清理单个缓存

### ISSUE THREAD

**Issue by gogooing** [hurshi/dio-http-cache#41]
你在插入缓存的时候key值使用了_getPrimaryKeyFromOptions转换，清除的时候并没有使用_getPrimaryKeyFromOptions转换，导致key值无法匹配，最好在清除的时候也用_getPrimaryKeyFromOptions转换，并且传递options.method。

**Comment by gogooing** [comment]
能否添加一个查询单个缓存的方法？

**Comment by zhancheng** [comment]
例子里面也是，用key和subkey清除都是提示清除失败

**Comment by gogooing** [comment]
我自己修改了下，支持了清除缓存和查询单个缓存

**Comment by hurshi** [comment]
您好，非常感谢您的反馈，也很抱歉我没有及时反应。
但是这个问题在 [0.2.8](https://pub.dev/packages/dio_http_cache) 中已经修复了。
欢迎试用新版本，有任何问题请在这里反馈。
再次感谢您的 issue。
