### ISSUE TITLE
Add documentation for baseUrl parameter in CacheConfig

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [hurshi/dio-http-cache#45]
Hi, I see `CacheConfig.baseUrl` as a parameter, but there's no documentation on what it's for. Could you explain the purpose of this parameter?

**Comment by ThinkDigitalSoftware** [comment]
Found that adding DioCacheManager(...).interceptor works. The docs need to be updated

**Comment by ThinkDigitalSoftware** [comment]
Sorry, I didn't scroll over to see it

**Comment by ThinkDigitalSoftware** [comment]
Repurposing this issue

**Comment by hurshi** [comment]
Hi, thanks for your issue;

I'm sorry for that, And I have updated README.
**baseUrl**: it’s optional; If you don't have set baseUrl in CacheConfig, when you call deleteCache, you need provide full path like "https://www.google.com/search?q=hello", but not just "search?q=hello".
