### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by nicoache1** [hurshi/dio-http-cache#51]
First of all thanks for your amazing package!

I see in the README that you need to enable and interceptor with a BaseUrl.
How this exactly works? is mandatory? I mean i can only set the CacheManager with no baseUrl?
All these questions arose because i have a case when I want to cache some requests but others don't, how do i should do that? set in the request maxAge to 0?

**Comment by MahdiPishguy** [comment]
+1

**Comment by hurshi** [comment]
Hi, thanks for your issue;
* baseUrl is optional;

* interceptors is required;

* Only requests that add the buildCacheOption will cache the data, like below:

  ```dart
  Dio().get(
    "http://www.google.com",
    options: buildCacheOptions(Duration(days: 7)),
  );
  ```
