### ISSUE TITLE
custom store and cache data view

### ISSUE THREAD

**Issue by Yonkers** [hurshi/dio-http-cache#53]
hope to add custom store and data view interface

**Comment by krisztianodor** [comment]
Yes, it would be great if we could somehow know if caching works at all the way it should without plugin hacking. The DioCacheManager needs some getter method.

**Comment by hurshi** [comment]
Hi, thanks for your issue;

#### I added two new features：

* Support database path custom config. 

  set databasePath in CacheConfig.

* Add flag in Response headers to distinguish whether the data is coming from the cache.

  ```dart
  // How to know if the data come from Cache
  if (null != response.headers.value(DIO_CACHE_HEADER_KEY_DATA_SOURCE)) {
   	// data come from cache
  } else {
   	// data come from net
  }
  ```
