### ISSUE TITLE
Best way to get / set cached data and skip http request completely?

### ISSUE THREAD

**Issue by kauaicreative** [hurshi/dio-http-cache#54]
Is there a simple way to retrieve the data from the cache and completely skip the http get request?

Not only access the cached data directly but also set the cached data directly?

**Comment by MahdiPishguy** [comment]
+1

**Comment by hurshi** [comment]
I'm sorry that there is no such way now.

### But

 You can set maxAge to a large number so that you can fetch the local cache each time. And **`forceRefresh`** when you need to fetch data from network.

**Comment by kauaicreative** [comment]
@hurshi That makes sense for getting the cached data and works perfectly. Still wish there was a simple way to overwrite the cached data in the sqlite database. Is the simplest way to connect directly to the database and overwrite via sqlite?
