### ISSUE TITLE
Window is full: requested allocation , SQLiteQuery( 8181): exception

### ISSUE THREAD

**Issue by hussamDana92** [hurshi/dio-http-cache#56]
Hi, 
what the solve this issue? 

> W/CursorWindow( 8181): Window is full: requested allocation 2302380 bytes, free space 2096582 bytes, window size 2097152 bytes
> E/SQLiteQuery( 8181): exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM cache_dio WHERE key="9ABF028761329D13B99AB053731C5957" and subKey="001B8DDA78776B8597AA53BFF7B36779"
> W/CursorWindow( 8181): Window is full: requested allocation 2302380 bytes, free space 2096582 bytes, window size 2097152 bytes
> E/SQLiteQuery( 8181): exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM cache_dio WHERE key="9ABF028761329D13B99AB053731C5957" and subKey="001B8DDA78776B8597AA53BFF7B36779"
> I/flutter ( 8181): DioError [DioErrorType.DEFAULT]: DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=1) sql 'SELECT * FROM cache_dio WHERE key="9ABF028761329D13B99AB053731C5957" and subKey="001B8DDA78776B8597AA53BFF7B36779"' args []}

**Comment by hurshi** [comment]
https://github.com/tekartik/sqflite/issues/270
Maybe you're trying to store a piece of data that's too big, an image or anything?

**Comment by danielweil** [comment]
How would you recommned trying to deal with this problem?
