### ISSUE TITLE
Is it possible to get data from the cache without passing the options parameter in requests?

### ISSUE THREAD

**Issue by guilhermedaldim** [hurshi/dio-http-cache#64]
Would I have to configure the cache directly through CacheConfig? And continue getting data from the offline cache?

It being not necessary to use the options parameter in all requests.

**Comment by hurshi** [comment]
Hello, Thanks for your issue.
Yes, it's necessary now. I think the developer must know what happened for every request. And 'cache data by default' is not a good way.
