### ISSUE TITLE
Add expiry date option

### ISSUE THREAD

**Issue by deadsoul44** [hurshi/dio-http-cache#68]
Thank you for the great package. Some data on server is updated with changing frequency. When making an api call, the expiry date is sometimes known. When a fixed refresh duration is set, it is possible to get outdated data from cache. Refresh duration can be set to the lowest possible but this will result in unnecessary api calls when data is updated on the server with less frequency. So, an optional expiry date parameter could be very useful.

**Comment by hurshi** [comment]
Hello, thanks for your feedback
It's not supported to modify the expiry date directly, but get maxAge from Cache-Control was supported.

> maxAge: set the cache time. If the value is null or not setted, it will try to get maxAge and maxStale from response headers.
