### ISSUE TITLE
cannot clear all cache

### ISSUE THREAD

**Issue by Marcosmaliki** [hurshi/dio-http-cache#70]
I can't clear all cache when the user logs out of the app. Here's my code
    `DioCacheManager cacheManager =
                      DioCacheManager(CacheConfig(baseUrl: baseUrl));
                  cacheManager.clearAll();`

I'm sorry if this has been asked and answered. Am I doing it wrong? Should I call   cacheManager.clearAll() asynchronously?

**Comment by hurshi** [comment]
Hello, thanks for your feedback,
Please try this: https://github.com/hurshi/dio-http-cache/issues/62
