### ISSUE TITLE
Caching dio download() results does not work

### ISSUE THREAD

**Issue by kbn** [hurshi/dio-http-cache#75]
dio.download() override [options.responseType = ResponseType.stream](https://github.com/flutterchina/dio/blob/master/dio/lib/src/entry/dio_for_native.dart#L80), which is not supported by dio-http-cache.

As a consequence, it is impossible to use the dio download() api call with dio-http-cache.

Possibly related to #65.

**Comment by hurshi** [comment]
Thanks for your issue. Duplicate of #65
