### ISSUE TITLE
MemoryCache is not invalidated when using deleteByPrimaryKey

### ISSUE THREAD

**Issue by tapkain** [hurshi/dio-http-cache#8]
Hello Hurshi. The memory is not invalidated because it should support "where" clause. Let me elaborate
_mapCache.invalidate("${key}_${subKey ?? ""}");
this line deletes only one record with the specified key and subkey, but what we actually want to achieve is to delete all the occurrences where key is present. So, it clears the disk cache, but the memory still stays the same.

**Comment by hurshi** [comment]
I'm terribly sorry. It was my fault. I have fixed the problem and updated the new version。
And thanks for your issue, have a nice day!

**Comment by tapkain** [comment]
Thank you 🙏
